# Generated by Django 6.0.4 on 2026-04-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_alter_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('published', 'Published'), ('draft', 'Draft')], default='pending', max_length=10),
        ),
    ]
